### ISSUE TITLE
Recursive File Type based alerting

### ISSUE THREAD

**Issue by ivantn21** [EmersonElectricCo/fsf#1]
Hello I'm seeking some help to identify best way to write a module that will set the alert flag if the parent is a compressed file (rar/zip) and the current file is an executable... Any thoughts?

**Comment by jxb5151** [comment]
Good question! I am actually pretty confident that this can be solved with Yara with its current capabilities. I'm going to hack on this a little and see what I come up with. Hopefully it addresses your needs!

**Comment by ivantn21** [comment]
Great! Thanks for the help! We saw the release and jumped to erite a custom
script for bro... Anddd in the few weeks will go on to prod! We like simple
and effective implementation! Great job!

Ivan

**Comment by jxb5151** [comment]
Thanks!

Try this on for size. I am still testing it, but it seems to do the trick so far on examples I have created. My only regret is that the rar file_header_part variable is not as exact as I would like it to be, but when I read the spec nothing else consistent seems to stand out, maybe I'll find inspiration later. To add and alert on this:
- add the signature to the dispositioner file on the server side and set your alert variable to true, something like... ('misc_compressed_exe', '', True),
- ensure it is also added to your rules.yara file and the sig is in the yara directory. 

Once I am satisfied with it, I will commit it to our yara sig list. Let me know what you think!

```
// Spec reference: http://forensicswiki.org/wiki/RAR#Format
rule compressed_exe_in_rar
{
   meta:
      author = "Jason Batchelor"
      company = "Emerson"
      lastmod = "20150813"
      desc = "Detect on evidence of a compressed executable within a RAR"

   strings:
      $rar = { 52 61 72 21 1A 07 00 }
      $file_header_part = { 74 [12] ( 00 | 01 | 02 | 03 | 04 | 05 ) [9] ( 30 | 31 | 32 | 33 | 34 | 35 ) }
      $exe_ext = ".exe"

   condition:
      $rar at 0 and for any r in (1..#file_header_part):
         // see if .exe is within the offset of the file archive header and however long the file name size is
         // file name begins 30 bytes away from start of header
         // file size is specified 24 bytes from the start
         ($exe_ext in (@file_header_part[r] + 30..@file_header_part[r] + 30 + uint16(@file_header_part[r] + 24)))
}

// Spec reference: https://en.wikipedia.org/wiki/Zip_(file_format)#File_headers
rule compressed_exe_in_zip
{
   meta:
      author = "Jason Batchelor"
      company = "Emerson"
      lastmod = "20150813"
      desc = "Detect on evidence of a compressed executable within a ZIP"

   strings:
      $pk = { 50 4B 03 04 }
      $exe_ext = ".exe"

   condition:
      $pk at 0 and for any p in (1..#pk):
         // see if .exe is within the offset of the local file header and however long the file name size is
         // file name begins 30 bytes away from the start of the local file header
         // file size is specified 26 bytes from the start
         ($exe_ext in (@pk[p] + 30..@pk[p] + 30 + uint16(@pk[p] + 26)))
}

rule misc_compressed_exe
{
   condition:
      compressed_exe_in_zip or compressed_exe_in_rar
}
```

**Comment by ivantn21** [comment]
That was quick, I will look in to it tomorrow and give you feedback, I like
what I see so far!

Ivan

**Comment by jxb5151** [comment]
Hey Ivan, 

So far this has fared well in my testing. I will close this out and formally commit this signature with another series of updates in the near future if that is okay.

**Comment by ivantn21** [comment]
great! thanks for taking the time we started testing and we are seeing good
results :-)

**Comment by jxb5151** [comment]
This has been placed into the latest commit. Consider it solved :)
