### ISSUE TITLE
wget errors when installing dependencies

### ISSUE THREAD

**Issue by peasead** [EmersonElectricCo/fsf#10]
On a fresh CentOS 7 - Minimal build, I got a lot of certificate errors when downloading the master.zip, Yara, and the RPMForge repo.

To fix this, you may want to include `--no-check-certificate` in the documentation when using wget.

**Comment by jxb5151** [comment]
Thanks for this, you may be doing something with SSL inspection at some point within your network that is causing problems with certificate validation? What you've done however is a good way to navigate past the issue. I've added a small note on this in the install document.
