### ISSUE TITLE
Using harcoded python paths is incompatibile with virtualenv

### ISSUE THREAD

**Issue by mpurzynski** [EmersonElectricCo/fsf#23]
Hey,

when trying to run fsf in a virtualenv, I noticed most files use hardcoded #!/usr/bin/python instead of #!/usr/bin/env python - thus it ignores the overwrite that virtualenv does.

Could you make fsf virtualenv compatible with this simple change? :)

**Comment by jxb5151** [comment]
Certainly! Thanks for bringing this up. Hopefully sometime after break.

**Comment by akniffe1** [comment]
merged in development branch.

**Comment by jxb5151** [comment]
Changed in master, noted in changelog. Thanks.
