### ISSUE TITLE
fsf-client [FILE] --noalert

### ISSUE THREAD

**Issue by JamesFerrer** [EmersonElectricCo/fsf#28]
to: @jxb5151 

Can we have something like --noalert?
Hoping this will override    "Alert": true
   },
    "Alert": true
}

Thanks! 
~jmes

**Comment by jxb5151** [comment]
Hey James. Take a look at enhancement #21 and the proposed changes which will do away with that key value all together. If that doesn't align with your thoughts, let us know.
