### ISSUE TITLE
Yum Error After Adding EPEL

### ISSUE THREAD

**Issue by peasead** [EmersonElectricCo/fsf#8]
I ran into an issue after adding the EPEL repo for CentOS 7 - Minimal.

After turning on the EPEL release `sudo yum install epel-release` I get the following error when doing `yum install python-pip ssdeep-devel`:
`Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again`

To fix this, I ran the following:
`sudo sed -i 's/https/http/g' /etc/yum.repos.d/epel.repo`

Not sure if this was just a me problem, but this fixed the issue.

**Comment by jxb5151** [comment]
I believe this directly relates to issue #10. Please see the solution there.
