### ISSUE TITLE
No netstat to check listening port

### ISSUE THREAD

**Issue by peasead** [EmersonElectricCo/fsf#9]
In CentOS 7 - Minimal, there is no netstat to check to ensure that the server is listening properly:

```
netstat -na | grep 5800
tcp        0      0 127.0.1.1:5800          0.0.0.0:*               LISTEN
```

It might be prudent to include the following in the dependencies for CentOS:
`yum install net-tools`

**Comment by jxb5151** [comment]
Thanks for this, I've updated the documentation to add this package.
